### ISSUE TITLE
11.05.18 Release

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-press#224]
## Dates
- Code freeze (no new features): **2018-10-26**
- Code deployed to staging server: 2018-10-30
- Testing on staging server: 2018-10-030 => 2018-11-05
- Code Released to Production: **2018-11-06**

## Link to release report
https://app.zenhub.com/workspace/o/connexions/webview/reports?report=release&release=5bbb8af0c068d7156510c830

## Repos updated:
oer.exports v0.65.0
webview v.0.40.0
cnx-recipes v1.18.0
cnx-press v7.0.1
nebuchadnezzar v7.1.0 
Products.RhaptosModuleEditor v0.93
cnx-db v2.6.0
cnx-archive v4.6.0
cnx-litezip v1.5.0

## Demo:
*(hyperlink the header above to the filter view for CNX milestone, release, and label: `rc-demo`)*
- 1
- 2

## Repo Checklist (Books+CNX)
- [ ] **oer.exports** (*Helene*)
	- [ ] https://github.com/Connexions/oer.exports/blob/master/version.txt should match current release
	- [ ] Release created in https://github.com/Connexions/oer.exports/releases
	- [ ] New RhaptosPrint egg should be built by DevOps (they need the version number)
- [ ] **cnx-recipes** (*Helene*)
	- [ ] Release created in https://github.com/Connexions/cnx-recipes/releases
	- [ ] cnx-deploy: `environments/__prod_envs/files/publishing-requirements.txt` should be updated -- a bot will automatically create this PR, which will need to be reviewed and merged.
- [ ] **webview** (*Helene*)
 	- [ ] Release created in https://github.com/Connexions/webview/releases
	- [ ] Tarball for version needs to be available at https://packages.cnx.org/js-builds/ (I think Jenkins builds this automatically?)
	- [ ] cnx-deploy: needs a manual PR opened, reviewed, and merged to update `environments/__prod_envs/vars/versions.yml`
- [ ] **nebuchadnezzar** (batch publishing client) (*Dante/Bryan/Ross*) - *no cnx-deploy change required*
 	- [ ] Release tag created in GitHub
	- [ ] PyPi version revved-- a bot will automatically create this PR, which will need to be reviewed and merged.
- [ ] **cnx-press** (*Ross*)
 	- [ ] Release tag created in GitHub
	- [ ] cnx-deploy: `environments/__prod_envs/vars/versions.yml` should be updated -- a bot will automatically create this PR, which will need to be reviewed and merged.
- [ ] more CNX repos here etc. -- full list here: https://github.com/Connexions/cnx/issues/8
- [ ] **cnx-archive** (*Ross*)
 	- [ ] Release tag created in GitHub
 	- [ ] PyPi version revved
	- [ ] cnx-deploy: 2 files need updating (a bot will automatically create this PR, which will need to be reviewed and merged):
		- ` environments/__prod_envs/files/archive-requirements.txt`
		- `environments/__prod_envs/files/publishing-requirements.txt` 
## Links to DevOps cards:
- staging
- prod

## Release Notes
**Batch**
- Image uploads via `neb publish`
- An alternative collection layout via the command line `-t`. This displays the titles of modules, sub-collections, and collections rather than the number

Further instructions on how to use the new features can be found in https://docs.google.com/document/d/1CuF_RKisaUY8_LOA9BmCLhwSlVSWCZB1L6e1el6mX8Y/edit#heading=h.foo55hr4nth1

This release requires the Neb client to be updated with special steps:
1. `brew install libmagic`
2. `pip install --upgrade nebuchadnezzar`
